services:
  db:
    image: mariadb:10.11
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlRootPassword
      - MYSQL_DATABASE=${SPIP_DB_NAME}
      - MYSQL_USER=${SPIP_DB_LOGIN}
      - MYSQL_PASSWORD=${SPIP_DB_PASS}

  app:
    image: erasme/spip-ccn:dev
    build:
      context: .
      args:
        - name=value
    restart: always
    volumes:
      - ./IMG/:/var/www/html/IMG
      - ./plugins/:/var/www/html/plugins
      - ./tmp/sessions/:/var/www/html/tmp/sessions
    links:
      - db:mysql
    env_file:
      - .env
    ports:
      - 8880:80