services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlRootPassword
      - MYSQL_DATABASE=spip
      - MYSQL_USER=spip
      - MYSQL_PASSWORD=spip

  app:
    image: erasme/spip-ccn:dev
    build:
      context: .
      args:
        - name=value
    restart: always
    volumes:
      - ./plugins/:/var/www/html/plugins
      - ./IMG/:/var/www/html/IMG
    links:
      - db:mysql
    environment:
      - SPIP_AUTO_INSTALL=0
      - SPIP_DB_SERVER=mysql
      - SPIP_DB_LOGIN=spip
      - SPIP_DB_PASS=spip
      - SPIP_DB_NAME=spip
      - SPIP_SITE_ADDRESS=http://localhost:8880
    ports:
      - 8880:80