apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: SPIP_AUTO_INSTALL
              value: "1"
            - name: SPIP_DB_LOGIN
              value: spip
            - name: SPIP_DB_NAME
              value: spip
            - name: SPIP_DB_PASS
              value: spip
            - name: SPIP_DB_SERVER
              value: mysql
            - name: SPIP_DB_HOST
              value: db
            - name: SPIP_SITE_ADDRESS
              value: http://localhost:8880
          image: erasme/spip-ccn:c7553d562a22924362be40ca39f23626047b9986
          name: app
          ports:
            - containerPort: 80
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /var/www/html/IMG
          #     name: app-cm1
      restartPolicy: Always
      # volumes:
      #   - configMap:
      #       name: app-cm1
      #     name: app-cm1
