apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: spip
            - name: MARIADB_PASSWORD
              value: spip
            - name: MARIADB_ROOT_PASSWORD
              value: MysqlRootPassword
            - name: MARIADB_USER
              value: spip
          image: mariadb:10.11
          name: db
      restartPolicy: Always
