apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccn-dev
spec:
  selector:
    matchLabels:
      app: ccn
  template:
    metadata:
      labels:
        app: ccn
    spec:
      volumes:
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.env.MYSQL_ROOT_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.env.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.env.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.env.MYSQL_PASSWORD }}
          image: {{ .Values.mariadb.image }}
          imagePullPolicy: Always
          name: mariadb
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Values.pvc.name }}
              subPath: mariadb-2
        - env:
            - name: SPIP_AUTO_INSTALL
              value: {{ .Values.spip.env.SPIP_AUTO_INSTALL }}
            - name: SPIP_DB_SERVER
              value: {{ .Values.spip.env.SPIP_DB_SERVER }}
            - name: SPIP_DB_LOGIN
              value: {{ .Values.spip.env.SPIP_DB_LOGIN }}
            - name: SPIP_DB_PASS
              value: {{ .Values.spip.env.SPIP_DB_PASS }}
            - name: SPIP_DB_NAME
              value: {{ .Values.spip.env.SPIP_DB_NAME }}
            - name: SPIP_SITE_ADDRESS
              value: {{ .Values.spip.env.SPIP_SITE_ADDRESS }}
            - name: SPIP_DB_HOST
              value: {{ .Values.spip.env.SPIP_DB_HOST }}
            - name: SPIP_ADMIN_PASS
              value: {{ .Values.spip.env.SPIP_ADMIN_PASS }}
            - name: SPIP_ADMIN_EMAIL
              value: {{ .Values.spip.env.SPIP_ADMIN_EMAIL }}
          image: {{ .Values.spip.image }}
          imagePullPolicy: Always
          name: spip
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/www/html/IMG
              name: {{ .Values.pvc.name }}
              subPath: spip-3