apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.name | default "ccn-ingress" }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | default "nginx" }}  
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.service.name | default "ccn-service" }}
                port:
                  number: 80