apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pvc.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
  accessModes:
    - ReadWriteOnce