apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name | default "ccn-service" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 80                         # External port exposed
      targetPort: 80                    # Container port (spip container is listening on 80)
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-ccn        # Target the spip application in the deployment