nameOverride: "custom-app"

pvc:
  name: "ccn-pvc"  # This gets prefixed by the release name in the templates
  storage: "1Gi"

mariadb:
  image: "mariadb:10.5"
  env:
    MYSQL_ROOT_PASSWORD: "MysqlRootPassword"
    MYSQL_DATABASE: "spip"
    MYSQL_USER: "spip"
    MYSQL_PASSWORD: "spip"

spip:
  image: "erasme/spip-ccn:dev"
  env:
    SPIP_AUTO_INSTALL: 1
    SPIP_DB_SERVER: "mysql"
    SPIP_DB_LOGIN: "spip"
    SPIP_DB_PASS: "spip"
    SPIP_DB_NAME: "spip"
    SPIP_SITE_ADDRESS: "www.example.com"
    SPIP_DB_HOST: "127.0.0.1"
    SPIP_ADMIN_PASS: "admin-pass"
    SPIP_ADMIN_EMAIL: "admin@example.com"
    #SPIP_VERSION_SITE: "fictions" # is not enabled will used thematique plugin

ingress:
  name: "ccn-ingress"
  host: "example.com"
  class: nginx