mariadb:
  image: mariadb:10.11
  env:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: spip
    MYSQL_USER: spip
    MYSQL_PASSWORD: mypass
    
spip:
  image: erasme/spip-ccn:dev
  env:
    SPIP_AUTO_INSTALL: 1
    SPIP_DB_SERVER: mysql
    SPIP_DB_LOGIN: spip
    SPIP_DB_PASS: mypass
    SPIP_DB_NAME: spip
    SPIP_SITE_ADDRESS: http://localhost:8080
    SPIP_DB_HOST: 127.0.0.1
    SPIP_ADMIN_PASS: password
    SPIP_ADMIN_EMAIL: admin@erasme.org

pvc:
  name: ccn-vol
  storage: 5Gi
  storageClass: svb-retain