name: Build and Push Docker Images

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  spip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: erasme/spip-ccn:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/spip-ccn:${{ github.sha }}

  redeploy:
    name: Redeploy Workloads
    runs-on: ubuntu-latest
    needs: spip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up workload list and Rancher URL
        id: vars
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=workloads::${{ secrets.WORKLOADS_PROD }}"
            echo "::set-output name=site::${{ secrets.RANCHER_PROD_URL }}"
          else
            echo "::set-output name=workloads::${{ secrets.WORKLOADS }}"
            echo "::set-output name=site::${{ secrets.RANCHER_DEV_URL }}"
          fi

      - name: Redeploy workloads
        run: |
          IFS="," read -ra ADDR <<< "${{ steps.vars.outputs.workloads }}"
          for i in "${ADDR[@]}"; do
            echo ${{ steps.vars.outputs.site }} | sed 's/./& /g'
            echo "Redeploying $i... ${{ steps.vars.outputs.site }}:${i}?action=redeploy "
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.RANCHER_TOKEN }}" \
              "${{ steps.vars.outputs.site }}:${i}?action=redeploy"
          done
