name: Update Version and build main branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main # This ensures that only PRs merged into 'main' will trigger this workflow.

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      ### Step 1: Check out the repository
      - name: Checkout Code
        if: ${{ github.event.pull_request.merged == true }}
        uses: actions/checkout@v3
      
      ### Step 2: Configure Git
      - name: Configure Git
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      ### Step 3: Bump the Version and Create Tag
      - name: Bump Version and Create Tag
        if: ${{ github.event.pull_request.merged == true }}
        id: version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 4.0.0
          DEFAULT_BUMP: patch

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: erasme/spip-ccn:latest , erasme/spip-ccn:${{ steps.version.outputs.new_tag }}
